### ISSUE TITLE
Would you please publish the package on PyPI?

### ISSUE THREAD

**Issue by furagu** [tutorcruncher/django-jinja-bootstrap-form#1]
It would be easier to install and keep track of requirements with pip.

**Comment by samuelcolvin** [comment]
I can do, but we use this in our requirements file:

```
-e git+https://github.com/samuelcolvin/django-jinja-bootstrap-form.git@bbceabb7832005568c6f863f68010795bdc9e5e7#egg=django_jinja_bootstrap_form-master == 4.0
```

~~I've just done a release so you should be able to use that instead of the commit sha~~

Cancel that, I'll submit it to pypi and release then.

**Comment by furagu** [comment]
Thanks a lot! :)

**Comment by samuelcolvin** [comment]
https://pypi.python.org/pypi/django-jinja-bootstrap-form/4.0.3
