### ISSUE TITLE
TemplateDoesNotExist error

### ISSUE THREAD

**Issue by eugenio** [tutorcruncher/django-jinja-bootstrap-form#5]
template:
> bootstrapform/form.jinja

was not found.

I'm using Django 1.11.4 all the packages are at the latest version.

Not really sure from where this error arise...

><form action"{{url('index')}}" method="post" enctype="multipart/form-data" class="form-inline">
     {% csrf_token %}
     {{ form|bootstrap_inline }}
     <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
 </form>

**Comment by samuelcolvin** [comment]
are you sue you have version `4.2.2` installed? have you added `bootstrapform_jinja` to your installed apps?

**Comment by eugenio** [comment]
@samuelcolvin  this is my settings's INSTALLED_APPS:
>    'gurpsdatabase.apps.GurpsdatabaseConfig',
    'django_extensions',
    'django_select2',
    'bootstrap4',
    'jinja2',
    'django_jinja',
    'bootstrapform_jinja',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

and this is my requirement.txt:
>Django==1.11.4
django-appconf==1.0.2
django-bootstrap4==0.0.1
django-extensions==1.8.1
django-jinja==2.3.1
django-jinja-bootstrap-form==4.2
django-model-urls==0.4.0
Django-Select2==5.11.1
generateDS==2.28a0
Jinja2==2.9.6
lxml==3.8.0
MarkupSafe==1.0
mysqlclient==1.3.10
pdb==0.1
pudb==2017.1.2
Pygments==2.2.0
python-gnupg==0.4.1
pytz==2017.2
PyYAML==3.12
six==1.10.0
urwid==1.3.1

As you can see the installed version is 4.2 not 4.2.2 is that making a difference?

EDIT: I think that the version installed from pip on python 3.5.3 (debian Stretch) is the 4.2 not the 4.2.2. I downloaded the package of the 4.2.2 but when I ried to install from the archive it failed saying the required python version is >= 3.6 which I clearly not meet.
Is there a workaround other than installing Python 3.6?

EDIT1: I forced the installation of the package with version 4.2.2 by changing the required version number of python in the conf file but I still get the same error.

**Comment by samuelcolvin** [comment]
We had this error in 4.2 and fixed it in 4.2.2 I believe, I also set the required version to 3.6 which I agree was a little over the top. I'll release a new version now which allows 3.5. 

I believe that should fix the problem.

**Comment by eugenio** [comment]
@samuelcolvin  thanks! Please let me know when the new version is out!

**Comment by samuelcolvin** [comment]
new version released: https://pypi.python.org/pypi/django-jinja-bootstrap-form/4.2.3

Please met me know if that fixes the problem.

**Comment by eugenio** [comment]
We are progressing! Now it throws another error:
TemplateSyntaxError at /uploadfile

[pastebin link](https://pastebin.com/bhHLgirG
)
 if you need more details please let me know!

**Comment by samuelcolvin** [comment]
looks to me like that template is being rendered with django's template engine not django-jinja.

Are you sure you have your settings such that django jinja is being used?

**Comment by samuelcolvin** [comment]
for reference here's the template section of TutorCruncher's settings:

```python
# =======================
#   Templates
# =======================
JINJA_TEMPLATE_BACKEND = 'django_jinja.backend.Jinja2'
if DJDB or TESTING:  # pragma: no cover
    JINJA_TEMPLATE_BACKEND = 'TutorCruncher.common.jinja_backend.Jinja2WithContext'

_TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'django.template.context_processors.debug',
    'django.template.context_processors.i18n',
    'django.template.context_processors.media',
    'django.template.context_processors.static',
    'django.template.context_processors.tz',
    'django.template.context_processors.request',
    'django.template.context_processors.csrf',
    'django.contrib.messages.context_processors.messages',
    'TutorCruncher.common.context.tc_basic',
)

TEMPLATES = [
    {
        'BACKEND': JINJA_TEMPLATE_BACKEND,
        'APP_DIRS': True,
        'DIRS': [os.path.join(DJ_DIR, 'templates')],
        'OPTIONS': {
            'match_extension': '.jinja',
            'trim_blocks': True,
            'lstrip_blocks': True,
            'constants': {
                'HELP_SITE_URL': HELP_SITE_URL,
                'USE_BUNDLED_STATICS': USE_BUNDLED_STATICS,
                'PASSWORD_MIN_LENGTH': PASSWORD_MIN_LENGTH,
                'GOOGLE_MAPS_BROWSER_KEY': GOOGLE_MAPS_BROWSER_KEY,
            },
            'context_processors': _TEMPLATE_CONTEXT_PROCESSORS
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'DIRS': [os.path.join(DJ_DIR, 'templates')],
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': _TEMPLATE_CONTEXT_PROCESSORS
        },
    },
]
JINJA2_BYTECODE_CACHE_ENABLE = True
```

Obviously you don't need all of that but the point is you need to setup your templates such that django-jinja is being used.

**Comment by eugenio** [comment]
What "DJ_DIR" is set to in your app case? is it the base app path?

**Comment by samuelcolvin** [comment]
`DJ_DIR = os.path.dirname(__file__)` the base directory for django code. 

The point is that in this case some templates live in a `templates` directory. You only need to use that directory if you're using a directory other than `<app>/templates`

**Comment by samuelcolvin** [comment]
I'm going to assume this is fixed as we're not having the problem and support for 3.5 is back in place, please comment again if you really can't solve your problems.

**Comment by eugenio** [comment]
I forgot that I didn't close the issue... My apologies. The error was fixed by the new release and the suggested template settings section stub!!!!
